baseurl: /
permalink: pretty
markdown: rdiscount

prose:
    rooturl: "_posts"
    media: "img"
    metadata:
        "_posts": |

            categories: post

            layout: post

            published: true

            invisible: true
